---
# - name: backup previous config
#   command: mv /etc/ceph/ceph.conf /etc/ceph/ceph.conf.bk-12-11-2018

- name: replace previous config
  copy: 
    src: files/ceph-jason.conf
    dest: /etc/ceph/ceph.conf

# - name: add line config 
#   lineinfile:
#     path: /etc/ceph/ceph.conf
#     state: present
#     line: 'mon clock drift allowed = 0.500000'


- name: restart ceph 
  systemd:
    name: ceph.target
    state: restarted

- name: pause 300 second
  pause: 
    seconds: 300